modLoader="javafml" #mandatory
loaderVersion="[26,)" #mandatory (26 is current forge version)
issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
modId="clumps" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Clumps" #mandatory
displayURL="http://example.com/" #optional
credits="" #optional
authors="Jaredlll08" #optional
description='''
Clumps xp orbs together.
'''
[[dependencies.examplemod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[27,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.3]"
    ordering="NONE"
    side="BOTH"