modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/jaredlll08/Clumps/issues"
license="MIT"
[[mods]] #mandatory
modId="clumps"
version="${file.jarVersion}"
displayName="Clumps"
displayURL="https://www.curseforge.com/minecraft/mc-mods/clumps"
updateJSONURL="https://updates.blamejared.com/get?n=clumps&gv=1.16.3"
credits=""
authors="Jaredlll08"
description='''
Clumps xp orbs together.
'''